
-- Startify
-- vim.cmd[[
-- let g:ascii = [
-- \'|\ |  _   _     .  _ _ ',
-- \'| \| (/_ (_) \/ | | | |']
-- function! Startify_quote()
-- 	let wrapped = []
-- 	for line in startify#fortune#quote()
-- 		let wrapped += split(line, '\%'.50.'c.\{-}\zs\s', 1)
-- 	endfor
-- 	return wrapped
-- endfunction
-- let g:startify_custom_header = 'startify#pad(g:ascii + [""] + Startify_quote() + [""])'
-- ]]
-- vim.g.startify_files_number = 5
-- vim.g.startify_bookmarks = {
-- 	{x = "~/.xinitrc"},
-- 	{c = "~/.config/"},
-- 	{v = "~/.config/nvim/"},
-- 	{p = "/media/TheAnes/Projects/"},
-- 	{t = "/media/TheAnes/Projects/TCD-Coursework/Year3/"}
-- }
-- vim.g.startify_commands = {
-- 	{u = {"Update Plugins", "PackerSync"} },
-- 	{l = {"Install LSP Servers", "LspInstallInfo"} }
-- }
-- vim.g.startify_lists = {
-- 	{ type = "files", header = {"   MRU"} },
-- 	{ type = "bookmarks", header = {"   Bookmarks"}      },
-- 	{ type = "commands",  header = {"   Commands"}       },
-- }
--
-- local alpha = require("alpha")
-- local startify = require("alpha.themes.startify")
-- startify.section.header.val = {
-- 	"|\\ |  _   _     .  _ _ ",
-- 	"| \\| (/_ (_) \\/ | | | |"
-- }
-- startify.section.top_buttons.val = {
-- 	startify.button("e", "  New file" , ":ene <BAR> startinsert <CR>"),
-- }
-- startify.section.mru_cwd.val = { { type = "padding", val = 0 } }

return { "goolord/alpha-nvim" }

