#!/bin/bash

# start polybars
primary_monitor="$(xrandr --query | grep " primary" | cut -d" " -f1)"
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
	if [ "$m" == "$primary_monitor" ]; then
		MONITOR="$m" polybar main &
		MONITOR="$m" polybar media &
	else
		MONITOR="$m" polybar secondary &
	fi
done
hudmanager &

# update backgrounds
feh --no-fehbg --bg-fill "$HOME/.config/wallpapers/wallpaper0.png" "$HOME/.config/wallpapers/wallpaper1.png"
